# Generated by Django 4.2.3 on 2023-08-17 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_advertisements', '0002_alter_advertisements_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisements',
            options={'verbose_name': 'Advertisements', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AddField(
            model_name='advertisements',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
